### ISSUE TITLE
Nog niet helemaal

### ISSUE THREAD

**Issue by Theo-denBlanken** [FirasSoekhai/FROj2O1#3]
Je komt al aardig dichterbij Firas, maar er is nog een kleine issue in class-namen zoals `container__profile__Picture`, namelijk er komt 2 keer `__` is dit soort namen voor. 
In BEM zit er maar 1 in per class-naam.
Want het deel voor de `__` heeft dezelfde class-naam als het blok. Je denkt dan dat is toch `container`? Dan zeg ik dat lijkt er zeker op want dit element zit inderdaad in een element met de naam `container`.    **Maar...**
Als ik naar de tweede `__`  in `container__profile__Picture` kijk dan is het linkerdeel daarvan `container__profile`. En gelukkig is er helemaal geen block met de naam `container__profile`.
Dus die tweede `__` is fout. 
Daarom is `container__profile-picture` een beter voorstel.
Dit geldt in gelijke mate voor de ander class-namen die bij jou 2 van die `__` hebben.

En dan ben ik nog op zoek naar een modifier....

**Comment by FirasSoekhai** [comment]
Ik heb de problemen met de `__` opgelost en veranderd naar `--` maar ik snap het modifier gedeelte niet helemaal. kunt u mij daar misschien meer uitleg over geven?
